apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: auth-service
  sessionAffinity: None
  type: LoadBalancer