--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  annotations: 
    deployment.kubernetes.io/revision: "1"
  labels: 
    app: auth-service
  name: auth-service
  namespace: default
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: auth-service
  strategy: 
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: auth-service
    spec: 
      containers: 
        - image: "urosvesic/auth-service:0.0.1-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          name: auth-service
          env:
            - name: AWS_CLIENT_ID
              valueFrom:
                configMapKeyRef :
                  name: auth-config
                  key: AWS_CLIENT_ID
            - name: AWS_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: AWS_CLIENT_SECRET
            - name: AWS_COGNITO_JWK
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: AWS_COGNITO_JWK
            - name: JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: JWT_ISSUER_URI
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-service
  name: auth-service
  namespace: default
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: auth-service
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion : v1
kind : ConfigMap
metadata:
  name: auth-config
data:
  AWS_CLIENT_ID:
  AWS_CLIENT_SECRET:
  AWS_COGNITO_JWK: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_WEmesG720/.well-known/jwks.json
  JWT_ISSUER_URI: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_WEmesG720
  

